### ISSUE TITLE
Support Substitutions

### ISSUE THREAD

**Issue by sasial-dev** [phuctm97/shell.how#138]
IE: `sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`

**Comment by sasial-dev** [comment]
this has *3* great examples of cases to support ^

**Comment by clo4** [comment]
Can be done relatively easily by integrating tree-sitter-bash. I'm planning to fork and add this (along with a more fully featured Fig spec parser I'm releasing soon 🤫)

**Comment by phuctm97** [comment]
> Can be done relatively easily by integrating tree-sitter-bash. I'm planning to fork and add this (along with a more fully featured Fig spec parser I'm releasing soon 🤫)

That would be 🔥
