### ISSUE TITLE
Fails to parse some commands

### ISSUE THREAD

**Issue by amorriscode** [phuctm97/shell.how#39]
Hey there!

It looks like we can break the command parsing pretty easily. Here are some examples:

- https://www.shell.how/tar%20xzf%20foo.tar.gz (`tar xzf foo.tar.gz`)
- https://www.shell.how/ls%20-lah (`ls -lah`)

**Comment by phuctm97** [comment]
Tks for reporting @amorriscode. A fix is shipped, the later command worked now!

**Comment by OlliePage** [comment]
Same thing here - try this: `cat $(find . -name "*.py") | grep -E -v '^\s*$|^\s*#' | wc -l` . The error is : `-n: option is unknown.` whereas on https://explainshell.com/ the website parses the command correctly. See: https://explainshell.com/explain?cmd=cat+%24%28find+.+-name+%22*.py%22%29+%7C+grep+-E+-v+%27%5E%5Cs*%24%7C%5E%5Cs*%23%27+%7C+wc+-l

**Comment by rafariva** [comment]
Using redirection >> Just mention it like an "argument"

**Comment by sasial-dev** [comment]
This also fails to parse `sudo` commands
