### ISSUE TITLE
v1.1

### ISSUE THREAD

**Issue by phuctm97** [phuctm97/shell.how#4]
Some of features would be really awesome to have in the next release 🚀:
- [ ] Parser: Handle single-quoted strings.
- [ ] Parser: Other improvements to make sure parser's first step always return correct number of tokens.
- [ ] Parser: Handle advanced syntax of options: grouped options, option using `=`
- [ ] Parser: Handle arguments with `isOptional`, `isPersistent`, `isRepeatable`, etc, differently.
- [ ] Performance: Install Fig's completion spec locally and static render first result → avoid (many) network calls client-side.
- [ ] SEO: Generate static sitemaps for all commands defined in spec → increase SEO, potentially make this the best place to search & learn shell command 🔥.
- [ ] Socials: Generate OG image dynamically for command being queried.

**Comment by Sepci0** [comment]
Bumping the `Parser: Handle advanced syntax` !

Wanted to try classic `rm -rf /` to look for easter eggs and i found out that `-rf`  option is unknown. 

Moreover, the error stops parsing because `rm -rf -v ` only shows the error instead of (at least) describing the -v option.

**Comment by caleb15** [comment]
same issue as Sepci0 with `ls -la --sort=date`

**Comment by phuctm97** [comment]
> Bumping the `Parser: Handle advanced syntax` !
> 
> Wanted to try classic `rm -rf /` to look for easter eggs and i found out that `-rf` option is unknown.
> 
> Moreover, the error stops parsing because `rm -rf -v ` only shows the error instead of (at least) describing the -v option.

@Sepci0 grouped options worked now!

**Comment by Almenon** [comment]
Can confirm ls -la works now, thanks.
