### ISSUE TITLE
Option is unknown with ls

### ISSUE THREAD

**Issue by Almenon** [phuctm97/shell.how#40]
I get an error with ls -la --sort=date

**Comment by phuctm97** [comment]
`--sort` is a non-standard option, for example when I run `ls -la --sort=date` on macOS, it will return a similar error
<img width="679" alt="CleanShot 2022-03-25 at 01 50 56@2x" src="https://user-images.githubusercontent.com/25026967/159989378-d4a8a449-0e38-4d72-838e-5f6e0cca5db3.png">

**Comment by Almenon** [comment]
I think it's worth supporting non-standard options if they are present in a very common distro like Ubuntu. Explainshell.com is able to give documentation for it, for example.
