### ISSUE TITLE
support for newer node version

### ISSUE THREAD

**Issue by craigz** [phuctm97/shell.how#6]
as a fig user i was excited to build and play with `shell.how` as well as considering it likely to be helpful in building/debugging fig completions.

however, the `node 14` requirement is a show-stopper as `V8 8.6` is required to build node for the arm64 architecture (for m1 macs) which as far as i know is only available in `node 15` and greater. 

while i know it is technically possible to run `node 14` in translated/rosetta mode, i'm not interested in pursuing that bag of hurt.

**Comment by phuctm97** [comment]
Thanks for the suggestion @craigz, a fix is pushed!
